### PR TITLE
Some implementations and changes

### PR DESCRIPTION
**Pull request by roubachof**
For our projects, we added some PCL fake, Xamarin implementations, and changed a bit things (created TypeForwarding.Xamarin in Net.Shim to split supported type in Xamarin AND NETFX from supported type in NETFX).
I don't know if it fits the philosophy of your shim :)

### CODE REVIEW

**Comment by anders9ustafsson** [comment]
Many thanks for helping out! I will review this as soon as possible. 

Best regards,
Anders @ Cureos

**Comment by anders9ustafsson** [comment]
@roubachof There are several code parts that seem relevant to add to _Shim_ in your PR, many thanks! But what is the specific reason for adding the _Xamarin_ "project"?

**Comment by roubachof** [comment]
@anders9ustafsson well the Xamarin project is an implementation of missing namespace in Xamarin. You can see that I splitted TypeForwarding.Net.cs into TypeForwarding.Net.cs and TypeForwarding.Xamarin.cs. TypeForwarding.Xamarin.cs contains all namespaces that are available in Xamarin AND NetFx. TypeForwarding.Net.cs contains namespaces available only in NetFx. So the Xamarin project give a basic implementation of those missing namespaces so projects will work in Xamarin targets. Doing that, I don't know if it complies to the philosophy of your lib, so merge what you want :)

**Comment by anders9ustafsson** [comment]
@roubachof Many thanks for sharing, and sorry I have not looked at this closely before.

Unfortunately, it its current form I am reluctant to pull this request, since it spans over too much at the same time, it violates some design ideas for _Shim_ (for example, I don't want to include any graphics related types like `Point`), and the API documentation is almost entirely missing.

So I am going to close this PR now, but feel free to re-post in smaller dedicated chunks so that it is possible to have a discussion on each part separately before accepting contributed code.

Regards,
Anders @ Cureos

**Pull request closed without merging**
